[package]
name = "nakdimon-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
eyre = "0.6.12"
ndarray = "0.16.1"
ort = "=2.0.0-rc.5"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
